[program:hamayesh-horizon]
process_name=%(program_name)s
command=/usr/bin/php /var/www/hamayesh/artisan horizon
directory=/var/www/hamayesh
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/hamayesh-horizon.log
stopwaitsecs=3600
user=www-data
